### ISSUE TITLE
We've deprecated OrgPreferences

### ISSUE THREAD

**Issue by bacigalupe** [rapsacnz/GeeWizz#1]
Hi,
trying to deploy this to my dev org, i get the following message. Could you please update your **project-scratch-def.json** file accordingly?

_ERROR running force:org:create: We've deprecated OrgPreferences. Update the scratch org definition file to replace OrgPreferences with their corresponding settings. Replace the orgPreferences section: { "orgPreferences": { "enabled": [ "S1DesktopEnabled" ], "disabled": [] } } With their updated settings: { "settings": { "lightningExperienceSettings": { "enableS1DesktopEnabled": true } } } For more info on configuring settings in a scratch org definition file see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs.htm._

![image](https://user-images.githubusercontent.com/2863938/71674795-82179680-2d7c-11ea-954f-e3754281683f.png)

Thanks!

**Comment by rapsacnz** [comment]
Ok done - thanks for letting me know!
